### PR TITLE
Try to leave the cursor in a sensible location on exit in Win32

### PR DESCRIPTION
**Pull request by malxau**
On Win32, exiting the editor leaves the cursor on a seemingly random line.

#### Background

- In the 70s, VT terminals allowed software to address characters visible on the screen.
- In the 80s, xterms added a scrollback capability but retained addressing characters by their visible location in the window.
- In the 90s, NT included scrollback capability without trying to be VT compatible, so addressed characters by their location within the entire scrollback buffer, not their location in the visible window.

In Win32, GetConsoleScreenBufferInfo returns the dimensions of the entire buffer including any vertical or horizontal scrolling (in dwSize), and the subset that is visible (srWindow.)

#### Issues

1. `switchcsbi` had code that attempted to set the cursor location when returning from the alternate screen buffer to the final line in the initial screen buffer.  This code was using the size of the buffer (including scrollback.)  It stored the initial cursor location in `cursinfo`, except...
2. `cursinfo` is overwritten in `ttysize` and `ttyresize`, containing the size of the buffer from the alternate buffer.  This has no scrollback, so the size of the buffer equals the size of the visible area, but...
3. `switchcsbi` is called from `ttywrite`, and `ttywrite` contains a local describing the cursor location and sets that location on function exit.  This location is relative to the alternate buffer, not the initial buffer, which would move the cursor up to the very top of the buffer, but also...
4. on exit, `ttysuspend` sends an explicit indication to position the cursor, and it's expecting to refer to the location relative to the viewing area, not the scrollback buffer.  This occurs if the terminal doesn't support restoring the terminal mode OR if the terminal is not xterm.

#### Changes

1. This change removes the code trying to set the cursor location in `switchcsbi` since it seems like it couldn't be doing anything.
2. This change uses a local in `ttysize` and `ttyresize`, although since the above change means the global isn't used, this isn't strictly needed.
3. This change has `switchcsbi` return the cursor location, so when switching buffers `ttywrite` can discover the implied cursor move as part of switching buffers.
4. This change removes the cursor move operation in `ttysuspend` if the terminal doesn't support restoring the terminal mode AND the terminal is not xterm.

The fourth part above is the part I'm least confident in and would affect non-Win32 systems.  It's not clear to me why the cursor would ever be explicitly positioned if the terminal supports restoring the terminal mode, so I don't know the purpose of the xterm check.

### CODE REVIEW

**Comment by ib** [comment]
> 4. This change removes the cursor move operation in ttysuspend if the terminal doesn't support restoring the terminal mode AND the terminal is not xterm.

> The fourth part above is the part I'm least confident in and would affect non-Win32 systems. It's not clear to me why the cursor would ever be explicitly positioned if the terminal supports restoring the terminal mode, so I don't know the purpose of the xterm check.

It it possible to run xterm without ti and te termcap support (titeInhibit).

To prevent positioning with other terminals, they should be explicitly named for testing.

**Comment by mbert** [comment]
I have cherry-picked your PR for now and will be using the code for my daily work for a while. I cannot comment on the change itself since I am vastly clueless on termcap programming. If anybody has an opinion (@ib?), please step forward :)

**Comment by ib** [comment]
From [Why doesn't the screen clear when running vi?](https://invisible-island.net/xterm/xterm.faq.html#xterm_tite):

> [...] However, xterms that are linked with termcap are more flexible in this area than those linked with terminfo libraries. The xterm program supports a resource titeInhibit which manipulates the $TERMCAP variable to accomplish this. It sets the $TERMCAP variable for the client with the ti and te capabilities suppressed. Systems that use terminfo cannot do this.

Apparently you would need an xterm linked with termcap to notice a difference.

Specifically naming and inserting terminals to the condition that should not perform cursor movement seems more sensible to me.

**Comment by malxau** [comment]
@ib Thanks for the pointer!

Ok, so with TI and TE, elvis displays on an alternate screen buffer.  On exit, it switches back to the regular screen buffer.  This leaves the cursor in the correct position, so this code avoids setting the cursor in this case.  This is the behavior that Win32 will have (wants to have?) also since it's using an alternate screen buffer unconditionally.

When I use titeInhibit, the behavior is to avoid using an alternate screen buffer, so elvis overwrites the display, and on exit leaves its text there, and wants to move the cursor to the bottom of the display.

I'm still a little puzzled though why any terminals need to be listed.  What it's trying to say is "if TE is in use, don't move the cursor" which is the first part of the test.  The second part of the test is saying, "always move the cursor on any terminal except those listed" which suggests that some terminals claim TE support and don't implement it correctly, and those terminals are not listed.  The terminals that are listed are the ones that claim to support it and are known to implement it correctly.

Anyway, I pushed a new commit to list both terminal types and restore the check to an or.

**Comment by mbert** [comment]
@malxau I have now cherry-picked your second commit and tried out the result. On my Mac in both stock Terminal and iTerm2 now the cursor will always be positioned at the very bottom after quitting elvis.

**Comment by malxau** [comment]
@mert To be clear, is that a behavior change? I'd expect that the original code would have done this.

**Comment by mbert** [comment]
> @mbert To be clear, is that a behavior change? I'd expect that the original code would have done this.

I have checked now. The original code did this (funny I never noticed). With your first commit it did no longer (I liked that better). Now it does it again.

**Comment by malxau** [comment]
*cringe*

Ok, I think I'm now convinced that a whitelist of known-good terminals is a bad idea.  Terminal.app reports itself as `xterm-color`, which is not `xterm`, so it's not known good, so elvis explicitly positions the cursor.  We can add `xterm-color` to the whitelist obviously, but it seems like an ominous path.

**Comment by ib** [comment]
Well, I had a look at who the "no cursor movement" code came from in the first place and - to my shame - I have to confess that I was the committer. Sorry.

I guess the idea at the time was to not cause problems with terminals I don't know, but clearly we should assume that terminals with te termcap capability can restore the screen.

The Issues (Win32 cursor location and te termcap capability handling) should be split into two patches for clarity. I take responsibility for my part with pull request #37.

**Comment by mbert** [comment]
Thank you. I have now been able to apply #36, #37 and #38. The code behaves OK as far as I can tell now. I would like to ask you guys, @malxau and @ib, to commend whether you see any problems in the proposed changes. As mentioned I am not enough proficient with termcap programming to make any decision on my own. If no showstopper is found by either of you I'll merge all three PRs tomorrow.

**Comment by mbert** [comment]
> I am not skilled enough in Windows programming to be able to judge the changes, but I personally would separate code changes from pure whitespace changes (tab instead of spaces) in two patches. That helps to better recognize what exactly needed to be changed. Just my opinion though.

Thank you, I agree that this is usually best practice. @malxau agreed?

Apart from that I cannot comment on Win32 changes either, so apart from the above I would see no reason not to merge the PR.

**Comment by malxau** [comment]
If you'd prefer me to keep formatting commits outside of substantive commits in future, I'll try my best.  Would you like me to split this PR too?  Currently formatting looks quite inconsistent, even within individual functions, so it's hard to look at a small piece of code without encountering misleading formatting.

On that note, I'd been moving code towards tabs instead of spaces since that seemed like the "primary" formatting technique - do you agree with this or should I go in the other direction?

As far as Win32, that's kind of my domain; I know a lot of open source users and developers aren't familiar with it, but I'm not sure the best thing I can do about that other than very clearly explain what I've observed, what I'm wanting to change, and why.  If there are questions I can answer about it that would be helpful, I'm more than willing.

By way of mini-bio, for my day job I've been working at Microsoft for the last >15 years; outside of work I maintain my own command prompt that leverages its terminal pretty heavily (http://www.malsmith.net/yori/) and more recently started moving up to TUI (eg. http://www.malsmith.net/edit/ )  Obviously there are things I don't know, but I have a fair bit of background working with the Win32 console/terminal and many/old versions of the Visual C++ toolchain.  The thing that brings me to this project is I used elvis a long time ago as version 1.4 was bundled with the Windows NT resource kit, including source, which I hacked up at the time to port to native Win32. I'm here since I know I can make this code run all old versions of Windows, and I'd like to see it run well.

**Comment by mbert** [comment]
@malxau if it gets too complicated I can live without splitting, just let me know.

As the indentation style is concerned it seems to be a tab-space mixture now (while a bit inconsistent in some parts). Typical code written at times when the editor would not automatically fix these things automatically when saving. 

When dealing with legacy code such as this I prefer not to change formatting for its own sake in order to keep the git history clean. So around code changes I'm fine with some modest formatting corrections.

**Pull request merged**
