### PR TITLE
Bring elvis.syn in sync with SSH-6.7

### PR DESCRIPTION
**Pull request by Tux**

### CODE REVIEW

**Comment by Tux** [comment]
Note that CamelCase in elvis.syn is currently ignored :( :(
dmsyntax.c should be enhanced to be able to use case-insensitive keywords

**Comment by ib** [comment]
What about using *ignorecase *?

**Comment by Tux** [comment]
ignorecase is already enabled in elvis.syn, but the keyword detection only lowercases the word to match, not the word to match against.

The better solution would be to amend the routine that reads elvis.syn and - detecting ignorecase - lowercare the keywords it already read. I do not have the tuits right now to do so.

As such, the pull-request is void, as it does only update the known keywords, but not the recognition of them.

**Comment by ib** [comment]
I was just wondering what you don't like with *ignorecase*.

Please see the documentation that says: "NOTE: When using "ignorecase true", you must give all keywords in lowercase."

**Comment by Tux** [comment]
Having the keywords in lowercase works - I had to do that - but it makes matching the documentation a *lot* harder. With the keywords in camelcase as the documentation of ssh_config lists them is making maint a lot easier.

**Pull request merged**
